### ISSUE TITLE
Filter layout

### ISSUE THREAD

**Issue by travis-robert** [ObjectiveSubject/Hester-Street#14]
Is it a huge pain layout-wise to tweak Services and Location tabs per spec below? I realize it's an unconventional / custom table structure, but it would look a lot nicer. ;)

![hs-filters](https://cloud.githubusercontent.com/assets/23262518/26269888/88c0469e-3cc5-11e7-9f8c-fd18fb7e3f2f.jpg)

**Comment by kpettinga** [comment]
@travis-robert in short, yes, this is a pain because the information for the filters is being grabbed in a bulk list, not in a partitioned way that accommodates your layouts. It would require us to sort and style (nearly) all the filter lists manually. Doing that sets you up to be dependent on the number of filters in each category for the layouts to work properly, so you run the risk of the layout breaking down the road when they want to add or remove filters.

**Comment by elliotarthur** [comment]
@kpettinga I'm noticing the category titles in these filters are all caps with spacing before the list of filters. Can the titles be upper-lower and remove the space after?

**Comment by kpettinga** [comment]
folding this into issue #28
