### ISSUE TITLE
Project location filter not working

### ISSUE THREAD

**Issue by kpettinga** [ObjectiveSubject/Hester-Street#52]
> the filter on these does not seem to be working, when you click on a neighborhood the all the projects stay but become faded out.

**Comment by Jessdwilson** [comment]
Also, this may be related. Anna wrote, "When searching by location, can we make it so that clicking on a borough loads all the neighborhoods within that borough?"
<img width="954" alt="screen shot 2017-06-06 at 10 18 55 am" src="https://cloud.githubusercontent.com/assets/1680051/26833852/9dedeae6-4aa1-11e7-9945-4cd10b95b2ca.png">

**Comment by kpettinga** [comment]
@Jessdwilson i've fixed this.

the issue was that there are certain location names (ie. queens, brooklyn, etc) that share words with project titles. For instance **location**: "Lower East Side" and **project**: "Lower East Side Ready".

This is causing the API that gets the list of projects to think that you actually want to visit the project page itself, not get a list of projects for that location. The temporary solution here is to rename the location **slugs** so that they can't be confused with project titles. I've done this for all the locations that were returning errors by prepending their slugs with "location-". The name of each location will stay the same so the front-end isn't affected.

I'm working on coming up with a better solution where they won't have to worry about location names and project titles being too similar. Closing for now.
